# Generated by Django 4.0.6 on 2022-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
