# Generated by Django 4.0.6 on 2022-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
