# Generated by Django 4.0.6 on 2022-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0002_despesas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevistos'), ('O', 'Outras')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='descricao',
            field=models.CharField(max_length=100, unique_for_month='data'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=100, unique_for_month='data'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
