# Generated by Django 4.0.6 on 2022-08-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0003_alter_despesas_categoria_alter_despesas_descricao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Receitas',
        ),
    ]
